# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestEleaniin' do
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Database', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

end

target 'TestEleaniin-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TestEleaniin-tvOS

  target 'TestEleaniin-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
